### ISSUE TITLE
when using "getResourcesTag" with "&tagSearchType=`exact`" I get no results when the resource has more than one tag

### ISSUE THREAD

**Issue by swbraun** [goldsky/SmartTag#25] opened 2015-04-14 15:42 UTC
To show all the resources for a specific tag I use the "getResourcesTag" snippet from tagLister.
Since I want to use tags that are similar (like "air" and "pair"), I tried to use the property "&tagSearchType=`exact`" which works when the resource has only one tag. If the resource has more than one tag, I get no results.
Here is my snippet call:
[[!getResourcesTag? 
    &parents=`50`
    &tagKey=`airSmartTag`
    &tpl=`air.SmartTagResults`
    &toPlaceholder=`results`
    &tagSearchType=`exact`
    &includeContent=`1`
    &includeTVs=`1`
    &showHidden=`1`
    &hideContainers=`1`
    &cache=`0`]]

If there is a built in functionality in SmartTag to achieve the same result as the "getResourcesTag" call, I'd be more than happy - unfortunately I couldn't find it.

**Comment by goldsky** [comment] 2015-04-15 11:20
I'll make the update

**Comment by goldsky** [comment] 2015-05-20 12:33
Hm... I think the problem is not on SmartTag.
`getResourcesTag`'s snippet call chains `getPage` & `getResources` snippets for the output.
`SmartTag` stores the tag's values delimited with double pipes (`||`) because it's the MODX's nature behavior for a custom TV.

May be you can try to add ``` &tvFiltersAndDelimiter=`||` ``` to the snippet's call as the trick?
But please switch over the ``` &tvFiltersOrDelimiter=`with_something_else` ``` because its default is indeed `||`.

**Comment by swbraun** [comment] 2015-05-20 14:23
This doesn't work.
But it seems the real problem is within ``getResources`` because it doesn't support these kind of queries.

I found a "hack" solution here: http://forums.modx.com/thread/?thread=82476&page=2
I used Bruno17´s alternative ``getResourcesTagExact`` snippet where I replaced
``"CONCAT(',',value,',') LIKE '%," . $tag . ",%'"`` with
``"CONCAT('||',value,'||') LIKE '%||" . $tag . "||%'"``
and it seems to work so far.

I'm not really into programming, so I don't know exactly what the problem is, but maybe you could offer an additional snippet with ``SmartTag`` which addresses this.

**Comment by goldsky** [comment] 2015-07-29 16:27
I'm closing this issue since it's more to be a `getResource`'s issue

**Closed by goldsky** 2015-07-29 16:27 UTC
